// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/diaspora-connect/EnvoiDiaspora.tsx": () => import("../components/mockups/diaspora-connect/EnvoiDiaspora.tsx"),
  "./components/mockups/diaspora-connect/ReceptionBenin.tsx": () => import("../components/mockups/diaspora-connect/ReceptionBenin.tsx")
};
